In [ ]:
import torch
import numpy as np

In [ ]:
torch.__version__

'2.0.1+cu118'

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


# Pass from NumPy to Tensor
Pay attention that these share the same area of memory.

In [ ]:
x = torch.from_numpy(arr)
x = torch.as_tensor(arr)
x[0]=-100

# x and arr share the same area of memory
print(x)
print(arr)

tensor([-100,    2,    3,    4,    5])
[-100    2    3    4    5]


In [ ]:
print(type(x))
print(x.type()) # this is more specific!

<class 'torch.Tensor'>
torch.LongTensor


<h2><a href='https://pytorch.org/docs/stable/tensors.html'>Tensor Datatypes</a></h2>
<table style="display: inline-block">
<tr><th>TYPE</th><th>NAME</th><th>EQUIVALENT</th><th>TENSOR TYPE</th></tr>
<tr><td>32-bit integer (signed)</td><td>torch.int32</td><td>torch.int</td><td>IntTensor</td></tr>
<tr><td>64-bit integer (signed)</td><td>torch.int64</td><td>torch.long</td><td>LongTensor</td></tr>
<tr><td>16-bit integer (signed)</td><td>torch.int16</td><td>torch.short</td><td>ShortTensor</td></tr>
<tr><td>32-bit floating point</td><td>torch.float32</td><td>torch.float</td><td>FloatTensor</td></tr>
<tr><td>64-bit floating point</td><td>torch.float64</td><td>torch.double</td><td>DoubleTensor</td></tr>
<tr><td>16-bit floating point</td><td>torch.float16</td><td>torch.half</td><td>HalfTensor</td></tr>
<tr><td>8-bit integer (signed)</td><td>torch.int8</td><td></td><td>CharTensor</td></tr>
<tr><td>8-bit integer (unsigned)</td><td>torch.uint8</td><td></td><td>ByteTensor</td></tr></table>

# Creating tensors from scratch
It is possible to use the factory function `torch.tensor` to create a tensor that has its own memory area (copy constructor).
If you do not pass the parameter of the data type `dtype`, you can use the specific constructors of the specific classes of the type. If you do not specify the data type, it is inferred by the input data.

In [ ]:
# to create a tensor from scratch
l = [1,2,3,4]
tensor = torch.tensor(l)
print(tensor)
print(tensor.dtype)
ftensor = torch.Tensor(l)
print(ftensor)
print(ftensor.dtype)
# we can change the data type of a given tensor
itensor = ftensor.type(torch.int64)
print(itensor.dtype)

tensor([1, 2, 3, 4])
torch.int64
tensor([1., 2., 3., 4.])
torch.float32
torch.int64


# Main attributes of a PyTorch tensor

In [ ]:
print(tensor.shape)
print(tensor.size()) # equivalent to tensor.shape
print(tensor.device)

torch.Size([4])
torch.Size([4])
cpu


In [ ]:
size = (3,4)
x = torch.empty(size)
print(x)
x = torch.zeros(size)
print(x)
x = torch.ones(size)
print(x)

tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28, 1.8176e+31],
        [7.2708e+31, 5.0778e+31, 3.2608e-12, 1.7728e+28],
        [7.0367e+22, 2.1715e-18, 1.3370e+22, 2.7004e-06]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### Tensors from ranges
<a href='https://pytorch.org/docs/stable/torch.html#torch.arange'><strong><tt>torch.arange(start,end,step)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.linspace'><strong><tt>torch.linspace(start,end,n. steps)</tt></strong></a><br>
Note that with <tt>.arange()</tt>, <tt>end</tt> is exclusive, while with <tt>linspace()</tt>, <tt>end</tt> is inclusive.

In [ ]:
x = torch.arange(0,18,2).reshape(3,3)
print(x)
x = torch.linspace(0,18,7)
print(x)
x = x.type(torch.int64)
print(x)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])
tensor([ 0.,  3.,  6.,  9., 12., 15., 18.])
tensor([ 0,  3,  6,  9, 12, 15, 18])


### Random number tensors
<a href='https://pytorch.org/docs/stable/torch.html#torch.rand'><strong><tt>torch.rand(size)</tt></strong></a> returns random samples from a uniform distribution over [0, 1)<br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randn'><strong><tt>torch.randn(size)</tt></strong></a> returns samples from the "standard normal" distribution [σ = 1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;Unlike <tt>rand</tt> which is uniform, values closer to zero are more likely to appear.<br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randint'><strong><tt>torch.randint(low,high,size)</tt></strong></a> returns random integers from low (inclusive) to high (exclusive)

In [ ]:
x = torch.rand(size)
print(x)
x = torch.randn(size)
print(x)
x = torch.randint(0,10,size)
print(x)

tensor([[0.7350, 0.7587, 0.5839, 0.7703],
        [0.3406, 0.1213, 0.8057, 0.4215],
        [0.0689, 0.7314, 0.4737, 0.2425]])
tensor([[-0.5005,  1.3234,  0.2933, -0.4112],
        [-0.3402, -1.8065, -0.2196, -1.5908],
        [-0.5445, -1.0333, -1.2227,  0.5173]])
tensor([[6, 1, 2, 0],
        [4, 5, 9, 8],
        [0, 9, 8, 4]])


# (Some) main operations between tensors

In [14]:
# addition
a = torch.ones(3,3)
b = torch.Tensor([1,2,3])
# : means all the elements, you can use None to add an axis
b = b[:,None]
print(b.shape)
o = torch.mm(a,b)
print(o)

o = a@b # equivalent to torch.mm(a,b)
print(o)

torch.Size([3, 1])
tensor([[6.],
        [6.],
        [6.]])
tensor([[6.],
        [6.],
        [6.]])


In [15]:
# element-wise multiplication (Hadamarad product)
o = a*b
print(o)
o = torch.mul(a, b)
print(o)

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])
tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])


In [23]:
c = torch.arange(0,10,1)
print(c.shape)
# reshape a tensor by choosing 2 rows and let PyTorch infer the correct dimension
# for the other axis
c = c.view(2,-1)
print(c)
# permute the axes
c = c.permute(1,0)
print(c)

torch.Size([10])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])
